version: '3'

services:
  nginx:
    build:
      context: frontend
      dockerfile: Dockerfile  # Path to your Dockerfile in the project root
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d  # Mount Nginx configuration
      - ./frontend/build:/static
    depends_on:
      - words_trainer
    networks:
      - my_network

  words_trainer:
    build:
      context: backend
      dockerfile: Dockerfile  # Path to your Dockerfile in the project root
    expose:
      - "9890"  # Expose the port within the Docker network
    volumes:
      - ./backend/db:/app/db  # Mount specific volume for words_trainer
    networks:
      - my_network

networks:
  my_network:
    driver: bridge